#Task 1

#Write a function called oops that explicitly raises an IndexError exception when called.
#Then write another function that calls oops inside a try/except state­ment to catch the error.
#What happens if you change oops to raise KeyError instead of IndexError?

def oops([i]):
    if list([i]) is out of range:
        raise Exception IndexError: 
return print('index is out of range')

Або 2 варіант 

def oops([i]):
    List =['2','3']
    if list([3]): 
   raise Exception IndexError: 
return print('index is out of range')

def catch_error:
    try: 
    list([i])
    except(oops([i]):
return print('index is out of range')

#Task 2

#Write a function that takes in two numbers from the user via input(), 
#call the numbers a and b, and then 
#returns the value of squared a divided by b, construct a try-except block 
#which raises an exception if the two values given by the input function were not numbers, 
#and if value b was zero (cannot divide by zero).    

def square_div(num1,num2):
    a = input('please enter a number: ')
    b = input('please enter a number: ')
    a,b = num1,num2
    try : 
          x = a**2/b
       if type(a) = str and type(b) = str:
            raise exception TypeError:
       print ('wrong data type. Please, enter a number')
    try : 
          x = a**2/b
      if b == 0 : 
          raise exception ZeroDivisionError:
print('Division by zero is prohibited')
