#Task 1

#Write a function called oops that explicitly raises an IndexError exception when called.
#Then write another function that calls oops inside a try/except stateÂ­ment to catch the error.
#What happens if you change oops to raise KeyError instead of IndexError?

def oops():
    qw= IndexError
    raise qw #this function raises IndexError 

def catch_error():
    try: 
        oops()
    except:
        print('Index error is caught')
 
print (catch_error()) 
# if we make oops raise KeyError
#def oops():
#    qwerty=KeyError
#    raise qwerty
#then our catch_error function will catch KeyError 

#Task 2

#Write a function that takes in two numbers from the user via input(), 
#call the numbers a and b, and then 
#returns the value of squared a divided by b, construct a try-except block 
#which raises an exception if the two values given by the input function were not numbers, 
#and if value b was zero (cannot divide by zero).    

def square_div(a,b):
    a = input('please enter a number: ')
    b = input('please enter a number: ')
  
    try : 
          x = a**2/b
       if type(a) = str and type(b) = str:
            raise exception TypeError:
            print ('wrong data type. Please, enter a number')
    try : 
          x = a**2/b
      if b == 0 : 
          raise exception ZeroDivisionError:
print('Division by zero is prohibited')
